name: picPics
description: picPics Application
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.8.0
  firebase_crashlytics: ^3.3.5
  firebase_messaging: ^14.6.7
  firebase_remote_config: ^4.2.5
  cloud_functions: ^4.4.0
  get: ^4.6.5
  supercharged: ^2.1.1
  simple_animations: ^5.0.2
  flutter_swiper_view: ^1.1.8
  cryptography: ^2.5.0
  photo_manager: ^2.7.1
  package_info_plus: ^4.1.0
  notification_permissions: ^0.6.1
  local_auth: ^2.1.6
  #date_utils: ^0.2.0
  devicelocale: ^0.6.0
  diacritic: ^0.1.4
  encrypt: ^5.0.1
  uuid: ^3.0.7
  geocoding: ^2.1.0
  drift: ^2.11.0
  path_provider: ^2.1.0
  path: ^1.8.3
  sqlite3_flutter_libs: ^0.5.16
  image: ^4.0.17
  flutter_branch_sdk: ^6.7.0
  facebook_app_events: ^0.19.0
  flutter_secure_storage: ^8.0.0
  home_widget: ^0.3.0
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2
  flutter_vibrate: ^1.3.0
  google_maps_flutter: ^2.4.0
  extended_image: ^8.1.0
  geolocator: ^10.0.0
  email_validator: ^2.1.17
  flutter_spinkit: ^5.2.0
  flare_flutter: ^3.0.2
  photo_view: ^0.14.0
  flutter_animator: ^3.2.2
  flutter_blurhash: ^0.7.0
  expandable: ^5.0.1
  background_fetch: ^1.2.1
  flutter_localization: ^0.1.13
  carousel_slider: ^4.2.1
  share_extend: ^2.0.0
  flutter_keyboard_visibility: ^5.4.1
  rate_my_app: ^2.0.0
  url_launcher: ^6.1.12
  share_plus: ^7.1.0
  percent_indicator: ^4.2.3
  auto_size_text: ^3.0.0
  convert: ^3.1.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  strings: ^2.0.3
  flutter_staggered_grid_view:
    git:
      url: https://github.com/suyulin/flutter_staggered_grid_view

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  drift_dev: ^2.11.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - lib/anims/
  fonts:
    - family: Lato
      fonts:
        - asset: lib/fonts/Lato-Bold.ttf
          weight: 700
        - asset: lib/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/fonts/Lato-Black.ttf
          weight: 900
        - asset: lib/fonts/Lato-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: lib/fonts/Lato-Light.ttf
          weight: 300
        - asset: lib/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/fonts/Lato-Thin.ttf
          weight: 100
        - asset: lib/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/fonts/Lato-Regular.ttf
          weight: 400
        - asset: lib/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
    - family: NotoSans
      fonts:
        - asset: lib/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: lib/fonts/NotoSans-Regular.ttf
          weight: 400