name: picPics
description: picPics application.
version: 1.1.1+136

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.1.3
  photo_view: ^0.9.2
  photo_manager: ^0.5.3+1
  flutter_swiper: ^1.1.6
  firebase_core: ^0.4.4+3
  rate_my_app: ^0.6.1+3
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.27+3
  hive:
  hive_flutter:
    git:
      url: git://github.com/hivedb/hive.git
      path: hive_flutter
  after_layout: ^1.0.7+2
  flutter_staggered_grid_view: ^0.3.0
  outline_gradient_button: ^1.0.0+2
  flutter_local_notifications: ^1.4.4+1
  firebase_messaging: ^6.0.15
  firebase_analytics: ^5.0.15
  firebase_crashlytics: ^0.1.3+3
  firebase_remote_config: ^0.3.0+3
  esys_flutter_share: ^1.0.2
  flutter_vibrate: ^1.0.0
  platform_alert_dialog: ^1.0.0+2
  notification_permissions: ^0.4.4
  firebase_admob: ^0.9.3+2
  flutter_keyboard_visibility: ^3.2.0
  purchases_flutter: ^1.1.0
  encrypt: ^4.0.1
  diacritic: ^0.1.1
  intl: ^0.16.1
  date_utils: ^0.1.0+3
  carousel_slider: 2.1.0
  expandable: ^4.1.4
  uuid: ^2.1.0
  url_launcher: ^5.4.11
  flare_flutter: ^2.0.3
  simple_animations: ^2.2.1
  flutter_device_locale: ^0.4.0
  package_info: ^0.4.1
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  hive_generator:
    git:
      url: git://github.com/hivedb/hive.git
      path: hive_generator

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - lib/anims/
  fonts:
    - family: Lato
      fonts:
        - asset: lib/fonts/Lato-Bold.ttf
          weight: 700
        - asset: lib/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/fonts/Lato-Black.ttf
          weight: 900
        - asset: lib/fonts/Lato-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: lib/fonts/Lato-Light.ttf
          weight: 300
        - asset: lib/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/fonts/Lato-Thin.ttf
          weight: 100
        - asset: lib/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/fonts/Lato-Regular.ttf
          weight: 400
        - asset: lib/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
    - family: NotoSans
      fonts:
        - asset: lib/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: lib/fonts/NotoSans-Regular.ttf
          weight: 400

flutter_intl:
  enabled: true
