name: picPics
description: picPics application.
version: 1.0.0+50

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.5
  photo_view: ^0.9.2
  photo_manager: ^0.5.0
  flutter_swiper: ^1.1.6
  firebase_core: ^0.4.4+3
  rate_my_app: ^0.6.0+2
  geolocator: ^5.3.1
  google_maps_flutter: ^0.5.26
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  after_layout: ^1.0.7+2
  flutter_staggered_grid_view: ^0.3.0
  outline_gradient_button: ^1.0.0+2
  flutter_local_notifications: ^1.4.1
  firebase_messaging: ^6.0.13
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.3+3
  firebase_remote_config: ^0.3.0+3
  esys_flutter_share: ^1.0.2
  flutter_vibrate: ^1.0.0
  platform_alert_dialog: ^1.0.0+2
  notification_permissions: ^0.4.4
  flutter_inapp_purchase: ^2.2.0
  firebase_admob: ^0.9.3+2
  keyboard_visibility: ^0.5.6

dependency_overrides:
  dartx: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.1

flutter:
  uses-material-design: true
  assets:
    - lib/images/
  fonts:
    - family: Lato
      fonts:
        - asset: lib/fonts/Lato-Bold.ttf
          weight: 700
        - asset: lib/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/fonts/Lato-Black.ttf
          weight: 900
        - asset: lib/fonts/Lato-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: lib/fonts/Lato-Light.ttf
          weight: 300
        - asset: lib/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/fonts/Lato-Thin.ttf
          weight: 100
        - asset: lib/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/fonts/Lato-Regular.ttf
          weight: 400
        - asset: lib/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
    - family: NotoSans
      fonts:
        - asset: lib/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: lib/fonts/NotoSans-Regular.ttf
          weight: 400
