name: picPics
description: picPics application.
publish_to: 'none'
version: 1.8.0+495

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.0
  collection: ^1.15.0-nullsafety.3
  provider: ^4.3.2+4
  extended_image: ^1.3.0
  photo_view: ^0.10.3
  photo_manager: ^0.6.0-dev.7
  flutter_swiper: ^1.1.6
  rate_my_app: ^0.7.2
  geolocator: ^6.1.9
  geocoding: ^1.0.5
  google_maps_flutter: ^1.1.0
  after_layout: ^1.0.7+2
  flutter_staggered_grid_view: ^0.3.2
  outline_gradient_button: ^1.0.0+2
  flutter_local_notifications: ^2.0.2
  firebase_core: 0.7.0
  firebase_messaging: 8.0.0-dev.13
  firebase_analytics: 7.0.1
  firebase_crashlytics: 0.4.0
  firebase_remote_config: 0.6.0
  firebase_auth: 0.20.0
  cloud_functions: 0.9.0
  firebase_ml_vision: 0.10.0
  flutter_vibrate: ^1.0.0
  platform_alert_dialog: ^1.0.0+2
  notification_permissions: ^0.4.8
  flutter_keyboard_visibility: ^4.0.2
  purchases_flutter: ^2.0.0
  diacritic: ^0.1.1
  intl: ^0.16.1
  date_utils: ^0.1.0+3
  carousel_slider: ^2.3.1
  expandable: ^4.1.4
  uuid: ^2.2.2
  url_launcher: ^5.7.10
  flare_flutter: ^2.0.6
  simple_animations: ^2.4.0
  flutter_device_locale: ^0.4.0
  package_info: ^0.4.3+2
  flutter_spinkit: ^4.1.2+1
  share_extend: ^1.1.9
  share: ^0.6.5+4
  esys_flutter_share: ^1.0.2
  mime: ^0.9.7
  path_provider: ^1.6.27
  bubble_bottom_bar: ^1.2.0
  flutter_inapp_purchase: ^3.0.1
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  flutter_animator: ^2.1.0
  email_validator: ^1.0.6
  flutter_secure_storage: ^3.3.4
  path: ^1.8.0-nullsafety.1
  cryptography_flutter: ^1.0.0
  convert: ^2.1.1
  encrypt: ^4.1.0
  flutter_branch_sdk: ^1.3.2
  facebook_app_events: ^0.8.2
  sliver_tools: ^0.1.9
#  tflite_flutter: ^0.5.0
#  tflite: ^1.1.1
  metadata: ^1.0.2
  showcaseview: ^0.1.6
  local_auth: ^0.6.3+4
  home_widget:
    git:
      url: git://github.com/leonardocustodio/home_widget.git
      ref: fix-build-ios
  background_fetch: ^0.6.0
  lottie: ^0.7.0+1
  moor: ^3.4.0
  sqlcipher_flutter_libs:
    git:
      url: https://github.com/simolus3/sqlite3.dart.git
      path: sqlcipher_flutter_libs
  #sqlite3_flutter_libs: ^0.3.0
  moor_db_viewer: ^2.0.3
  hive: ^1.4.4+1
  hive_flutter:
    git:
      url: git://github.com/hivedb/hive.git
      path: hive_flutter

dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  test: 1.16.0-nullsafety.5
#  mockito: 4.1.2
#  faker: 1.2.1
  build_runner: ^1.10.3
  mobx_codegen: ^1.1.2
  hive_generator: ^0.8.1
#  image: ^2.1.4
  googleapis: ^0.56.1
  googleapis_auth: any
  strings: ^0.1.2
  moor_generator: ^3.4.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - lib/anims/
  fonts:
    - family: Lato
      fonts:
        - asset: lib/fonts/Lato-Bold.ttf
          weight: 700
        - asset: lib/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/fonts/Lato-Black.ttf
          weight: 900
        - asset: lib/fonts/Lato-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: lib/fonts/Lato-Light.ttf
          weight: 300
        - asset: lib/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/fonts/Lato-Thin.ttf
          weight: 100
        - asset: lib/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/fonts/Lato-Regular.ttf
          weight: 400
        - asset: lib/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
    - family: NotoSans
      fonts:
        - asset: lib/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: lib/fonts/NotoSans-Regular.ttf
          weight: 400

flutter_intl:
  enabled: true
