name: picPics
description: picPics application.
publish_to: 'none'
version: 1.9.0-kawal10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  percent_indicator: ^3.0.1
  #autocomplete_textfield: 1.7.3
  #blurhash_dart: 0.2.3
  #bubble_bottom_bar: 1.2.0
  #cryptography_flutter: 2.0.0
  #extended_image: ^1.3.0
  #firebase_ml_vision: 0.12.0
  #flutter_mobx: ^1.1.0+2
  #flutter_swiper: 1.1.6
  #flutter_vibrate: 1.0.0
  #get: ^3.26.0
  #google_ml_kit: ^0.6.0
  #metadata: 1.0.2
  #mobx: ^1.2.1+4
  #provider: ^4.3.2+4
  #shimmer: 1.1.2
  #sqlite3_flutter_libs: ^0.3.0
  #tflite_flutter: ^0.5.0
  #tflite: ^1.1.1
  after_layout: 1.1.0
  background_fetch: 1.0.0
  carousel_slider: 4.0.0-nullsafety.0
  cloud_functions: 1.1.2
  collection: 1.15.0
  cryptography: 2.0.0
  cupertino_icons: 1.0.3
  date_utils: 0.2.0
  diacritic: 0.1.3
  email_validator: 2.0.1
  encrypt: 5.0.0
  expandable: 5.0.1
  extended_image: 4.1.0
  facebook_app_events: 0.12.0
  firebase_analytics: 8.1.2
  firebase_auth: 1.4.1
  firebase_core: 1.3.0
  firebase_crashlytics: 2.0.6
  firebase_messaging: 10.0.2
  firebase_remote_config: 0.10.0+2
  flare_flutter: 3.0.1
  flutter_animator: 3.1.1
  flutter_blurhash: 0.6.0
  flutter_branch_sdk: 3.2.0
  flutter_inapp_purchase: 5.0.1
  flutter_keyboard_visibility: 5.0.2
  flutter_secure_storage: 4.2.0
  flutter_spinkit: 5.0.0
  flutter_staggered_grid_view: 0.4.0
  geocoding: 2.0.0
  geolocator: 7.1.0
  get: ^4.3.0
  google_maps_flutter: 2.0.6
  hive: 2.0.4
  home_widget: 0.1.2+1
  image: 3.0.2
  local_auth: 1.1.6
  lottie: 1.0.1
  mime: 1.0.0
  moor_db_viewer: 4.0.0
  notification_permissions: 0.5.0
  outline_gradient_button: 2.0.0+1
  package_info: 2.0.2
  path: 1.8.0
  photo_manager: 1.2.2
  photo_view: 0.11.1
  pull_to_refresh: 2.0.0
  purchases_flutter: 3.3.0
  rate_my_app: 1.1.0+1
  share_extend: 2.0.0
  share: 2.0.4
  showcaseview: 1.0.0
  simple_animations: 3.1.1
  sliver_tools: 0.2.5
  url_launcher: 6.0.6
  uuid: 3.0.4
  #flutter_sticky_header: ^0.6.0
  #visibility_detector: 0.2.0
  flutter_vibrate:
    git:
      url: https://github.com/justkawal/flutter_vibrate.git
  autocomplete_textfield:
    git:
      url: https://github.com/justkawal/flutter-autocomplete-textfield.git
  bubble_bottom_bar:
    git:
      url: https://github.com/justkawal/bubble_bottom_bar.git
  platform_alert_dialog:
    git:
      url: https://github.com/justkawal/platform_alert_dialog
  cryptography_flutter:
    git:
      url: https://github.com/justkawal/cryptography.git
      path: cryptography_flutter
  flutter_device_locale:
    git:
      url: https://github.com/justkawal/flutter_device_locale.git
  flutter_swiper:
    git:
      url: https://github.com/justkawal/flutter_swiper.git
  #flutter_staggered_grid_view:
  #  git:
  #    url: git://github.com/justkawal/flutter_staggered_grid_view.git
  #home_widget:
  #  git:
  #    url: git://github.com/leonardocustodio/home_widget.git
  #    ref: fix-build-ios

dependency_overrides:
  intl: ^0.17.0
  flutter_local_notifications: ^7.0.0-dev.1
  flutter_local_notifications_platform_interface: 4.0.0
  path_provider: ^2.0.0
  convert: 3.0.0
  moor: 4.3.2
  hive_flutter: ^1.0.0
  crypto: 3.0.1
  #hive_flutter:
  #  git:
  #    url: git://github.com/justkawal/hive.git
  #    path: hive_flutter
  #    ref: 59ad5403593283233d922f62f76832c64fa33a3b
  sqflite:
    git:
      url: git://github.com/justkawal/sqflite_sqlcipher.git
      path: sqflite 
      ref: bb2b0a
      #ref: fmdb_override
  #moor_ffi:
  #  git:
  #    url: git://github.com/justkawal/moor.git
  #    #ref: beta 
  #    ref: 85206d
  #    path: moor_ffi
  moor_ffi: ^0.8.0
  ffi: ^1.1.2
  #sqlcipher_flutter_libs: ^0.5.0

dev_dependencies:
  #faker: 1.2.1
  #image: ^2.1.4
  #mobx_codegen: ^1.1.2
  #mockito: 4.1.2
  #test: 1.16.0-nullsafety.5
  build_runner: 2.0.4
  googleapis_auth: 1.1.0
  googleapis: 3.0.0
  hive_generator: 1.1.0
  moor_generator: 4.3.1
  strings: 0.2.1

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - lib/anims/
  fonts:
    - family: Lato
      fonts:
        - asset: lib/fonts/Lato-Bold.ttf
          weight: 700
        - asset: lib/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/fonts/Lato-Black.ttf
          weight: 900
        - asset: lib/fonts/Lato-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: lib/fonts/Lato-Light.ttf
          weight: 300
        - asset: lib/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/fonts/Lato-Thin.ttf
          weight: 100
        - asset: lib/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/fonts/Lato-Regular.ttf
          weight: 400
        - asset: lib/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
    - family: NotoSans
      fonts:
        - asset: lib/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: lib/fonts/NotoSans-Regular.ttf
          weight: 400

flutter_intl:
  enabled: true
