// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOi_EL0ROIiKFpFqqzGm6FnREYTMdhiwY',
    appId: '1:782873848258:android:9c6e970f39f436db1f8e5b',
    messagingSenderId: '782873848258',
    projectId: 'picpics',
    databaseURL: 'https://picpics.firebaseio.com',
    storageBucket: 'picpics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhp_u5mFTZiedLTOtaLoD20w55Ya6JSLM',
    appId: '1:782873848258:ios:7db595160b6b6e9e1f8e5b',
    messagingSenderId: '782873848258',
    projectId: 'picpics',
    databaseURL: 'https://picpics.firebaseio.com',
    storageBucket: 'picpics.appspot.com',
    androidClientId: '782873848258-sqj0psl71h0v1ou6ubjovtae0bssdobg.apps.googleusercontent.com',
    iosClientId: '782873848258-1r809shqf1tg3n1hpabgmlqfngtf41bk.apps.googleusercontent.com',
    iosBundleId: 'br.com.inovatso.picPics',
  );
}
