# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build"
  lane :beta do
    #gradle(task: "clean assembleRelease")
    #crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here

    # build the release variant
    build_android_app(task: "assembleRelease")

    # changelog from a txt file is passed as the release note
    #changelog = File.read("../changelog.txt")

    # submit build to firebase app distribution
    #firebase_app_distribution(
    #    app: "1:782873848258:android:9c6e970f39f436db1f8e5b",
    #    release_notes: "New beta build",
    #    groups: "picpics",
    #    apk_path: "/Users/custodio/FlutterProjects/picpics/build/app/outputs/apk/release/app-release.apk",
    #    firebase_cli_path: "/Users/custodio/.nvm/versions/node/v8.17.0/bin/firebase",
    #)

    upload_to_play_store(
        track: "internal",
        aab: "/Users/custodio/FlutterProjects/picpics/build/app/outputs/bundle/release/app-release.aab",
        skip_upload_changelogs: true,
        skip_upload_apk: true,
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        skip_upload_aab: false,
    )

  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

